### ISSUE TITLE
Bug Fix Package Manager

### ISSUE THREAD

**Issue by ViniciusDeep** [ViniciusDeep/WPImage#7]
<img width="675" alt="Screen Shot 2019-10-05 at 10 33 17" src="https://user-images.githubusercontent.com/32227073/66255578-93400f80-e75b-11e9-8bdf-0579fa9f53a7.png">

**Comment by phucnm** [comment]
@ViniciusDeep I fixed it and created a PR. However I accidentally added tag 1.0.0 with no changes, now the last version is 1.0.1.
